
networks:
  sensorhandling:
    driver: bridge

volumes:
  kafka-data:
    driver: local
  db-data:
    driver: local
  redis-data:
    driver: local
  debezium-data:
    driver: local

services:
  generator:
    image: 'jambbo/data-generator-microservice'
    networks:
      - sensorhandling
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8081:8081'

  analyser:
    image: 'jambbo/data-analyser-microservice:latest'
    networks:
      - sensorhandling
    depends_on:
      - db
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '8082:8082'

  store:
    image: 'jambbo/data-store-microservice:latest'
    networks:
      - sensorhandling
    depends_on:
      - debezium
      - redis
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DEBEZIUM_KAFKA_BROKER_ID=${DEBEZIUM_KAFKA_BROKER_ID}
    ports:
      - '8083:8083'


  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - sensorhandling
    environment:
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_PROCESS_ROLES=${KAFKA_PROCESS_ROLES}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_CONTROLLER_QUORUM_VOTERS}
      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_CONTROLLER_LISTENER_NAMES=${KAFKA_CONTROLLER_LISTENER_NAMES}
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - CLUSTER_ID=${CLUSTER_ID}
    ports:
      - '9094:9094'
    volumes:
      - kafka-data:/var/lib/kafka/data

  db:
    image: 'postgres:15.1-alpine'
    container_name: postgres
    networks:
      - sensorhandling
    env_file:
      - .env
    ports:
      - '5437:5432'
    command: #will write the data what changes are going on and we will be able to read and process it
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-alpine
    networks:
      - sensorhandling
    env_file:
      - .env
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning #Save the dataset to disk every 20 seconds if at least 1 key has changed.
    volumes:
      - redis-data:/data

  debezium:
    image: 'debezium/connect:2.4.0.Final'
    networks:
      - sensorhandling
    depends_on:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - GROUP_ID=${DEBEZIUM_KAFKA_BROKER_ID}
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    user: root
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://kafka:9092" ]
#      interval: 30s
#      retries: 5
    volumes:
      - debezium-data:/debezium/data
      - ./data-generator-microservice/connector/conf/:/on-startup/  #place folder conf into on-startup folder