spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

server:
  port: 8082

topics: data-temperature,data-power,data-voltage
