spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    bootstrap-servers: kafka:9092
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true

server:
  port: 8082

topics: data-temperature,data-power,data-voltage