
networks:
  sensorhandling:
    driver: bridge

volumes:
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local
  db-data:
    driver: local
  redis-data:
    driver: local

services:
  generator:
    image: 'jambbo/data-generator-microservice:latest'
    networks:
      - sensorhandling
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - '8081:8081'

  analyser:
    image: 'jambbo/data-analyser-microservice:latest'
    networks:
      - sensorhandling
    depends_on:
      - db
      - kafka
    env_file:
      - .env
    ports:
      - '8082:8082'


  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    networks:
      - sensorhandling
    env_file:
      - .env
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    networks:
      - sensorhandling
    depends_on:
      - zookeeper
    env_file:
      - .env
    ports:
      - '9092:9092'
    volumes:
      - kafka-data:/var/lib/kafka/data

  db:
    image: 'postgres:15.1-alpine'
    container_name: postgres
    networks:
      - sensorhandling
    env_file:
      - .env
    ports:
      - '5437:5432'
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - db-data:/var/lib/postgresql/data


