spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: local-group

topics: data-temperature,data-power,data-voltage